version: '2'

services:

  collector1:
    image: twitter-heat-collector:latest
    container_name: collector1
    environment:
      - "NODE_HOSTNAME=collector1"
      - "CLUSTER_PORT=3001"
      - "TWITTER_HEAT_ROLE1=collector"
      - "TWITTER_HEAT_ROLE2=worker"
      - "TWITTER_HEAT_ROLE3=statsManager"
      - "TWITTER_CONSUMER_KEY=[consumer key]"
      - "TWITTER_CONSUMER_SECRET=[comsumer secret]"
      - "TWITTER_ACCESS_TOKEN=[access token]"
      - "TWITTER_ACCESS_TOKEN_SECRET=[access token secret]"

    ports:
      - "3001:3001"

  collector2:
      image: twitter-heat-collector:latest
      container_name: collector2
      environment:
        - "NODE_HOSTNAME=collector2"
        - "CLUSTER_PORT=3002"
        - "TWITTER_HEAT_ROLE1=collector"
        - "TWITTER_HEAT_ROLE2=worker"
        - "TWITTER_HEAT_ROLE3=statsManager"
        - "TWITTER_CONSUMER_KEY=[consumer key]"
        - "TWITTER_CONSUMER_SECRET=[consumer secret]"
        - "TWITTER_ACCESS_TOKEN=[access token]"
        - "TWITTER_ACCESS_TOKEN_SECRET=[access token secret]"
      ports:
        - "3002:3002"
      depends_on:
        - collector1

  api1:
      image: twitter-heat-api:latest
      container_name: api1
      environment:
        - "NODE_HOSTNAME=api1"
        - "CLUSTER_PORT=3011"
      ports:
        - "3011:3011"
        - "8080:8080"
      depends_on:
        - collector1


